# Generated by Django 4.0.3 on 2022-03-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='name', max_length=50)),
                ('mobile_number', models.BigIntegerField(help_text='mobile_number')),
                ('email', models.EmailField(help_text='email', max_length=50)),
                ('date', models.DateField(help_text='date')),
                ('time', models.TimeField(help_text='time')),
                ('type_of_address', models.CharField(help_text='type_of_address', max_length=200)),
                ('home_address', models.CharField(help_text='home_address', max_length=200)),
                ('parlour', models.CharField(help_text='parlour', max_length=200)),
                ('beautician', models.CharField(default='True', help_text='beautician', max_length=50)),
                ('members', models.CharField(help_text='members', max_length=10)),
                ('service', models.CharField(help_text='service', max_length=20, null='True')),
                ('status', models.CharField(default='pending', max_length=50, null='True')),
                ('reg_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'customer_appoinment',
            },
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('Customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter Your Name', max_length=50)),
                ('password', models.CharField(help_text='Enter Your Password', max_length=50)),
                ('mobile_number', models.BigIntegerField(help_text='Enter Your mobile_number')),
                ('email', models.EmailField(help_text='Enter Your email', max_length=50)),
                ('image', models.ImageField(null=True, upload_to='logo/images/')),
                ('status', models.CharField(default='pending', max_length=50, null=True)),
                ('reg_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'customer_details',
            },
        ),
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='name', max_length=50)),
                ('email', models.EmailField(help_text='email', max_length=50)),
                ('feedback', models.TextField(help_text='feedback', max_length=350, null=True)),
                ('reg_date', models.DateField(auto_now_add=True, null=True)),
                ('customer_image', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'customer_feedback',
            },
        ),
    ]
