# Generated by Django 4.0.3 on 2022-03-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='location',
            field=models.CharField(help_text='Location', max_length=200, null=True),
        ),
    ]
