# Generated by Django 4.0.3 on 2022-03-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0002_customermodel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='birthday',
            field=models.BigIntegerField(help_text='Date of Birthday', null=True),
        ),
    ]
