# Generated by Django 4.0.3 on 2022-03-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0003_customermodel_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='birthday',
            field=models.DateField(help_text='Date of Birthday', null=True),
        ),
    ]
