# Generated by Django 4.0.3 on 2022-03-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0004_alter_customermodel_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='birthday',
            field=models.CharField(help_text='Date of Birthday', max_length=50, null=True),
        ),
    ]
