# Generated by Django 4.0.3 on 2022-04-01 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlourapp', '0002_alter_parlourmodel_table'),
        ('customerapp', '0006_alter_customermodel_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='parlour_model',
            field=models.ForeignKey(blank=True, db_column='parlour_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parlourmodel', to='parlourapp.parlourmodel'),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='parlour',
            field=models.CharField(help_text='parlour_name', max_length=200),
        ),
    ]
