# Generated by Django 4.0.3 on 2022-04-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0007_appointmentmodel_parlour_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='parlour_model',
        ),
    ]
