# Generated by Django 4.0.3 on 2022-04-01 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlourapp', '0002_alter_parlourmodel_table'),
        ('customerapp', '0008_remove_appointmentmodel_parlour_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='parlour_model',
            field=models.ForeignKey(blank=True, db_column='parlour_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parlourmodel', to='parlourapp.parlourmodel'),
        ),
    ]
