# Generated by Django 4.0.3 on 2022-04-04 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0009_appointmentmodel_parlour_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='customer_model',
            field=models.ForeignKey(blank=True, db_column='Customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customermodel', to='customerapp.customermodel'),
        ),
    ]
