# Generated by Django 4.0.3 on 2022-03-31 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParlourModel',
            fields=[
                ('parlour_id', models.AutoField(primary_key=True, serialize=False)),
                ('parlour_name', models.CharField(help_text='Enter Your Name', max_length=50)),
                ('email', models.CharField(help_text='Enter Your email', max_length=50, null=True)),
                ('password', models.CharField(help_text='Enter Your Password', max_length=50)),
                ('confirmpassword', models.CharField(help_text='confirmpassword', max_length=50, null=True)),
                ('mobile', models.BigIntegerField(help_text='Enter Your mobile_number')),
                ('address', models.CharField(help_text='Enter Your address', max_length=200)),
                ('license', models.ImageField(upload_to='images/logo/')),
                ('logo', models.ImageField(upload_to='logo/images/')),
                ('status', models.CharField(default='pending', max_length=50, null=True)),
                ('reg_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'beautician_details',
            },
        ),
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('beautician_name', models.TextField(help_text='beautician name', max_length=100, null=True)),
                ('service_name', models.CharField(help_text='service_name', max_length=50)),
                ('price', models.CharField(help_text='price', max_length=50)),
                ('message', models.TextField(help_text='message', max_length=200)),
                ('service_image', models.ImageField(null=True, upload_to='services/')),
                ('beautician_image', models.ImageField(null=True, upload_to='beauticians/')),
                ('service_date_added', models.DateField(auto_now_add=True, null=True)),
                ('parlour', models.ForeignKey(blank=True, db_column='parlour_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parlour', to='parlourapp.parlourmodel')),
            ],
            options={
                'db_table': 'parlour_services',
            },
        ),
    ]
