# Generated by Django 4.0.3 on 2022-04-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='reg_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
